### ISSUE TITLE
Query regarding inputs of rout_vic.py 

### ISSUE THREAD

**Issue by LSRathore** [KMarkert/servir-vic-training#10]
Hi,
Inputs for rout_vic.py (which is routing script) requires following input file locations:
gauge unit hydrograph 
fraction file
runoff data
baseflow data
output streamflow file
start time 
end time
boolean out daily data
Could someone please explain me more about the **fraction file**? Whether it should a text file or a raster file. If it's a raster file, then should it be of the whole area or just for one station?
Thanks

**Comment by KMarkert** [comment]
Hi @lokendrarathore, the input for the fraction file is a geotiff where each pixel is the fraction of area in that pixel that the watershed covers. For example, a pixel in the middle of a watershed will have a value of 1. A pixel where the watershed only covers half will have a value of 0.5.
It is important to note that the fraction file is at the same spatial resolution as the model runs and covers the entire domain as the model run. It is used to figure out which grid cells should be used in the routing model and how much of the runoff is contributed.
Please let me know if this helps clarify!

**Comment by LSRathore** [comment]
Hi @KMarkert thanks, that for clarifying. 
Further, I have one more doubt regarding the rout_vic.py . My basin contains four stations at which I need to estimate discharge. What we used to do in the older routing model, which was developed in Fortran, is to specify (in a text file) the station at which want discharge values.
Here in the python code of routing rout_vic , do we simulate stationwise?

**Comment by KMarkert** [comment]
@lokendrarathore you are correct with the original routing model you supply the gauge locations and the model the calculates which model grid cells contribute to the gauges. By supplying the grid fraction tiff file this calculation is circumvented. You can simply create multiple grid fraction tiff files for all of your gauges in the basin and run the `rout_vic.py` with the different gauge grid fractions files.
Hopefully this makes sense. Please let me know if I can help further clarify.

**Comment by LSRathore** [comment]
Hi @KMarkert  I have another query regarding script _format_meteo_forcing.py_ for making forcing files. It needs a NetCDF file which consists of rainfall, tmax, tmin, and wind velocity and in the code, it converts the temperature to celsius from kelvin. But, the precipitation default unit is meter of era data, so it needed to be converted in to mm, as vic takes precipitation in mm. Where did you convert that in the script.
Thanks.

**Comment by KMarkert** [comment]
@lokendrathore since this next question isn't related to the routing inputs I am going to open up a new issue. Please let me know if you have any additional questions here on the routing model, otherwise we can call this one closed.

**Comment by KMarkert** [comment]
I am assuming this question is resolved so I am closing now. Please reopen if there are any additional questions related to the `rout_vic` functionality.
