### ISSUE TITLE
Error in run

### ISSUE THREAD

**Issue by hoseinsalehi** [KMarkert/servir-vic-training#13]
Hello
I went from the first step to the run of the model with the data you put yourself (Niyando basin) with the new scripts you created two months ago.
But in the implementation phase of the model, I encountered a problem that I sent to you with a screen shot.
![runerror](https://user-images.githubusercontent.com/38522226/56853678-5cf69c80-6940-11e9-953e-47c9813a0994.png)

**Comment by abthom** [comment]
Change the number of snow bands to 10 in the global parameter file to reflect the snow bands referenced in the snow.param file

**Comment by hoseinsalehi** [comment]
@abthom thank you for your attention
I acted as you said and got the number of snow bands, but I got into error.
![error2](https://user-images.githubusercontent.com/38522226/56999858-48c3d100-6bc6-11e9-89ba-6aa35a3c0bd6.png)

**Comment by hoseinsalehi** [comment]
@abthom Thank you for your attention.
I acted as you said and increased the number of snow bands to 10, but I encountered an error.
![error2](https://user-images.githubusercontent.com/38522226/57000002-ec14e600-6bc6-11e9-9f5a-50386b0af987.png)

**Comment by abthom** [comment]
@hoseinsalehi 
![Snow ParamFile](https://user-images.githubusercontent.com/30537057/57003708-22823f00-6b8e-11e9-9de0-97624cc5ad48.jpg)
Just to be clear, the number 10 came from the snow.param file in data/input/snow.param. I would open that file up and make sure 10 reflects the number of snow bands your file is referencing. Please see the attached image for reference (showing my snow.param file and a count on snow bands).

**Comment by hoseinsalehi** [comment]
I supplied the snow param file using the scripts, but I do not think this file is properly formed.
I've uploaded an image of the file.
![snow param](https://user-images.githubusercontent.com/38522226/57181712-5b7f2400-6eac-11e9-853e-a174c33fbaa8.png)

**Comment by KMarkert** [comment]
@hoseinsalehi it seems that you are missing data for cells 1-6 where it is showing all 0. There is probably other cells with missing data.

I would check to make sure that the spatial coverage of your elevation dataset that you are using to create the snow.param file aligns with the grid that you are using to set up the model.

**Comment by hoseinsalehi** [comment]
@KMarkert 
I use nyando_basin data which you put them.
I run all the steps carefully and several times, but the outputs were this.
I have attached them.
[params.zip](https://github.com/KMarkert/servir-vic-training/files/3161175/params.zip)

**Comment by fang1103** [comment]
Hi, @hoseinsalehi 

Sorry to open this discussion again. But I am facing exactly the same problem with you (I've obtained all the parameters files mostly similar with yours for the nyando_basin dataset). Have you solved this problem? Thanks!
