### ISSUE TITLE
inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by solomonsg** [KMarkert/servir-vic-training#14]
Dear all, 

thanks for the examples files. while all goes well, I am having a problem with creating the snow parameters for the Nyando basin. 
I used this: 
python format_snow_params.py ../data/input/gis/Nyando_grid.tif ../data/input/gis/Nyando_basin_SRTM_snap.tif ../data/input/snow.param 100

the error is: 
File "format_snow_params.py", line 108
    tmp=tmp2[:]
              ^
TabError: inconsistent use of tabs and spaces in indentation

Can anyone help with this

Best, 

Solomon

**Comment by solomonsg** [comment]
I solved it with autopep8 format_snow_params.py.

**Comment by KMarkert** [comment]
@solomonsg I will make a note to run `autopep8` on the format_snow_params.py file and push online so others don't run into the issue. Thanks for solving!
