### ISSUE TITLE
About Gauge Watershed

### ISSUE THREAD

**Issue by Mrkoirala** [KMarkert/servir-vic-training#20]
@KMarkert: Hellow sir, what does "Gauge Watershed" excatly mean?? and how to prepare it?

**Comment by qingling-bao** [comment]
How to calculate the gauge watershed

**Comment by KMarkert** [comment]
The gauge watershed is the contributing basin (all area upstream that flows through the point on the channel). This can be calculated using [GIS software and some hydrologic analysis](https://docs.qgis.org/2.8/en/docs/training_manual/processing/hydro.html). After the basin is calculated a fractional area at the resolution of the model needs to be calculated where 1 = whole grid cell runoff contributes, 0 = no grid cell runoff contribute. This can usually be done using a resample with mean operator or by using the [snap_raster.py](https://github.com/KMarkert/servir-vic-training/blob/master/scripts/snap_raster.py) script.

Here is an example where the raster is the gauge watershed for the gauge, yellow triangle:

<img width="1023" alt="Screen Shot 2020-09-01 at 2 19 44 PM" src="https://user-images.githubusercontent.com/11776290/91896308-3d6f3280-ec5e-11ea-9b89-b54529bb6a23.png">

**Comment by qingling-bao** [comment]
Hello, I have some doubts. Regarding the VIC model, the watershed runoff recharge I studied mainly relies on the recharge of glacial snowwater meltwater, but in this example only surface runoff and base flow are considered. How to increase the impact of glacier snowwater runoff recharge?


On 09/2/2020 03:21，Kel Markert<notifications@github.com> wrote：

The gauge watershed is the contributing basin (all area upstream that flows through the point on the channel). This can be calculated using GIS software and some hydrologic analysis. After the basin is calculated a fractional area at the resolution of the model needs to be calculated where 1 = whole grid cell runoff contributes, 0 = no grid cell runoff contribute. This can usually be done using a resample with mean operator or by using the snap_raster.py script.

Here is an example where the raster is the gauge watershed for the gauge, yellow triangle:
