### ISSUE TITLE
Format meteorological forcing files

### ISSUE THREAD

**Issue by qingling-bao** [KMarkert/servir-vic-training#25]
When I run Format meteorological forcing files 
($ python format_meteo_forcing.py ../data/input/gis/Nyando_grid.tif ../data/input/forcing/raw/ ../data/input/forcing/ 2005 2013) I get The following error:
   File "format_meteo_forcing.py", line 166
     print'Processing time: {0}'.format(dt)
                                ^
SyntaxError: invalid syntax
How to solve this problem?

**Comment by KMarkert** [comment]
This is a Python2.7 vs Python3 error. If you are using Python3 then the print statement should be wrapped in parentheses like this:`print("Processing time: {0}'.format(dt)")`

This is a general issue for other scripts as well since I used Python2.7 at the time of writing. If you run into this error again then just update the print statements within the script to be valid Python3 syntax.

**Comment by qingling-bao** [comment]
Think for your answer ! I have solv this issue 

发送自 Windows 10 版邮件应用

发件人: Kel Markert
发送时间: 2020年7月27日 21:31
收件人: KMarkert/servir-vic-training
抄送: HurriCaneBQL; Manual
主题: Re: [KMarkert/servir-vic-training] Format meteorological forcingfiles (#25)

This is a Python2.7 vs Python3 error. If you are using Python3 then the print statement should be wrapped in parentheses like this:print("Processing time: {0}'.format(dt)")
This is a general issue for other scripts as well since I used Python2.7 at the time of writing. If you run into this error again then just update the print statements within the script to be valid Python3 syntax.

**Comment by KMarkert** [comment]
Great! Glad you were able to resolve it. Let me know if I can help answer any other questions. 🙂

**Comment by HurriCaneBQL** [comment]
Prof.Markert:
          Dear Prof.Kel ,I appreciate you feedback information on VIC-training. Due to the recent preparation of a doctoral dissertation, I need to use the VIC model. I encountered a lot of difficulties in this. Fortunately, I found the information about the vic model you shared on the Internet.When preparing meteorology data, I have a few doubts 🤔

(1)Below is your Git forcing folder,Where is nyando_era_met_data.nc downloaded from? Do I need to preprocess it myself? How to preprocess this data?

(2)The scripts folder contains 4 scripts related to  meteorology preprocessing,. What do they mean, and which one is the most important?
(3)What is the difference between the chirps folder and the persiann folder? Is persiann just enough?

         Again really appreciate your help !!😄
