### ISSUE TITLE
snap_raster.py: 'Error setting output data type'

### ISSUE THREAD

**Issue by Tarikbouram** [KMarkert/servir-vic-training#5]
Hello
I'v been trying lately to use your Nyando basin tutorial, to familiarize myself with the VIC model.
I encounter this issue with the 'snap_raster.py' command:
"
 python snap_raster.py ../data/input/gis/Nyando_basin_SRTM_filled.tif ../data/input/gis/Nyando_basin_SRTMSnap.tif ../data/input/gis/Nyando_grid.tif True bilinear
Traceback (most recent call last):
  File "snap_raster.py", line 143, in <module>
    main()
  File "snap_raster.py", line 137, in main
    snap_raster(sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4],sys.argv[5])
  File "snap_raster.py", line 74, in snap_raster
    raise KeyError('Error setting output data type')
KeyError: 'Error setting output data type'

"

**Comment by KMarkert** [comment]
The original script was expecting the input raster to be of a specific data type. The script has been updated in the repo to fix this problem. Please try using it again with the updated script and post results.

**Comment by Tarikbouram** [comment]
I used the updated script and there are no problems reported with snap_raster.py. Thank you
