### ISSUE TITLE
routing in servir-vic-training

### ISSUE THREAD

**Issue by hoseinsalehi** [KMarkert/servir-vic-training#8]
Hi
I use servir-vic-training-master to learning vic hydrology model.
but there is error in rout section.
what can i do?
I attached error
![screenshot from 2018-10-15 14-22-48](https://user-images.githubusercontent.com/38522226/47523035-f1a21400-d8a3-11e8-9287-b1cf7b067fe2.png)

**Comment by KMarkert** [comment]
Hi, it looks like you are getting an indentation error at line 290 because of either a missing indent or too far indented. Can you please try downloading [a fresh copy of the script](https://github.com/KMarkert/servir-vic-training/blob/master/scripts/rout_vic.py) and re-run your analysis?
Please let me know if that helps or not.

**Comment by hoseinsalehi** [comment]
Hi,I used the modified text but the result was as follows.
#################################################################
python rout_vic.py ../data/input/Nyando_UHFile.csv ../data/input/gis/Nyando_gauge_fraction.tif ../data/output/runoff_2005.nc ../data/output/base_2005.nc ../data/output/rout_out.csv 20050101 20131231 False
  File "rout_vic.py", line 290
    main()
       ^
IndentationError: expected an indented block
#################################################################
I've sent you a version of the NetCDF file.
################################################################
This netCDF 4.6.0 has been built with the following features: 

  --cc        -> /usr/bin/cc
  --cflags    -> -I/usr/include -I/usr/include/hdf5/serial
  --libs      -> -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lnetcdf -lhdf5_hl -lhdf5 -lpthread -lsz -lz -ldl -lm -lcurl

  --has-c++   -> no
  --cxx       -> 

  --has-c++4  -> no
  --cxx4      -> 

  --has-fortran-> no
  --has-dap   -> yes
  --has-dap2  -> yes
  --has-dap4  -> yes
  --has-nc2   -> yes
  --has-nc4   -> yes
  --has-hdf5  -> yes
  --has-hdf4  -> no
  --has-logging-> no
  --has-pnetcdf-> no
  --has-szlib -> no
  --has-cdf5 -> no
  --has-parallel-> no

  --prefix    -> /usr
  --includedir-> /usr/include
  --libdir    -> /usr/lib/x86_64-linux-gnu
  --version   -> netCDF 4.6.0
#######################################################################
thank you for your attention.

**Comment by hoseinsalehi** [comment]
Hi,I used the modified text but the result was as follows.
#################################################################
python rout_vic.py ../data/input/Nyando_UHFile.csv
../data/input/gis/Nyando_gauge_fraction.tif ../data/output/runoff_2005.nc
../data/output/base_2005.nc ../data/output/rout_out.csv 20050101 20131231
False
File "rout_vic.py", line 290
main()
^
IndentationError: expected an indented block
#################################################################
I've sent you a version of the NetCDF file.
################################################################
This netCDF 4.6.0 has been built with the following features:

--cc -> /usr/bin/cc
--cflags -> -I/usr/include -I/usr/include/hdf5/serial
--libs -> -L/usr/lib/x86_64-linux-gnu
-L/usr/lib/x86_64-linux-gnu/hdf5/serial -lnetcdf -lhdf5_hl -lhdf5 -lpthread
-lsz -lz -ldl -lm -lcurl

--has-c++ -> no
--cxx ->

--has-c++4 -> no
--cxx4 ->

--has-fortran-> no
--has-dap -> yes
--has-dap2 -> yes
--has-dap4 -> yes
--has-nc2 -> yes
--has-nc4 -> yes
--has-hdf5 -> yes
--has-hdf4 -> no
--has-logging-> no
--has-pnetcdf-> no
--has-szlib -> no
--has-cdf5 -> no
--has-parallel-> no

--prefix -> /usr
--includedir-> /usr/include
--libdir -> /usr/lib/x86_64-linux-gnu
--version -> netCDF 4.6.0
#######################################################################
thank you for your attention.

‫‪Kel Markert‬‏ <‪notifications@github.com‬‏> در تاریخ دوشنبه ۲۹ اکتبر ۲۰۱۸
ساعت ۱۹:۳۶ نوشت:‬

**Comment by hoseinsalehi** [comment]
Hello all.
The rout_vic.py is working correctly.
Thanks dear @KMarkert for his efforts and support.
